### PR TITLE
Fix(171): Proposal list subscribe 

### LINKED ISSUE #171: [BUG] Proposals list page not updating on chain state change
## Overview

The proposals list on the home screen doesn't update when there are state changes on chain.

The service should be subscribed to changes

### PR DESCRIPTION
**Pull request by RyRy79261**
## Description

This PR swaps the suspense hook to use the standard Apollo query hook which allows for auto polling.

## Testing

I used a local instance & the development instance to create a proposal on the development instance & watch on the local instance for changes

## Notes

This removes suspense logic, this could be resolved by tightly binding to the loading state of the query. However, given that we will be refactoring to React Query/Tanstack for GraphQL in future, allocating time to a soon to be removed package simply for a loading bar to appear seems low priority

## Related issues

- closes #171

### CODE REVIEW

**Comment by nvtaveras** [comment]
Tested this and it looked fine for the list of proposals, however the state above that shows the # of proposal, voters, total veMento was a bit clunky. Don't have exact repro steps but switching back and forth a few times the # of voters was not updated properly after switching from alfajores to mainnet and it was remaining at 7

**Review by chapati23 — CHANGES_REQUESTED** [review]
I can't even navigate to a proposal details page on this PR, i.e. try https://governance-pn6h80a5w-mentolabs.vercel.app/proposals/76852543598626010309184355681141482743859825585547539168614458156040950326608

I'm getting this in the console 
image

**Review by chapati23 — APPROVED** [review]
aight, works now!

**Comment by RyRy79261** [comment]
> Don't have exact repro steps but switching back and forth a few times the # of voters was not updated properly after switching from alfajores to mainnet and it was staying

@nvtaveras I'm not following, what was switching and what page were you on where you expected proposal data not to change when changing the network?

**Review by chapati23 — APPROVED** [review]
tested that voting does update the proposal list without full reload now 👍

**Comment by bayological** [comment]
> > Don't have exact repro steps but switching back and forth a few times the # of voters was not updated properly after switching from alfajores to mainnet and it was staying
> 
> @nvtaveras I'm not following, what was switching and what page were you on where you expected proposal data not to change when changing the network?

It's definitely a weird one but I believe it's unrelated to the changes here.  I was able to reproduce it once and have added an issue with steps [here](https://github.com/mento-protocol/governance-ui/issues/176). However this is very low priority so we should address it later.

**Review by bayological — APPROVED** [review]
LGTM 👍

**Pull request merged**
