### PR TITLE
Fix(173): Darkmode explainer

### LINKED ISSUE #173: [BUG] Dark mode for explainer text in the Execution step of proposal creation not implemented
## Overview

The dark mode colors need to be set for the execution example modal

### PR DESCRIPTION
**Pull request by RyRy79261**
## Description 

This PR updates the modal to use the typical dark mode colors 

## Testing

Basically switch to dark mode, go to create proposal, check the explainer modal on the code section in step 3

Then try create a proposal, but dont sign the transaction, check if the loading modal is correct, then decline signing the create proposal transaction, and see if the retry modal is correct as well

## Related issues 

- closes #173

### CODE REVIEW

**Comment by nvtaveras** [comment]
Seems fine but is the blue in `Unfortunately, transaction was rejected.` correct? Seems hard to read

Screenshot 2024-06-06 at 16 41 33

**Review by baroooo — COMMENTED** [review]
I agree with nelson, looks good apart from the hard to read text

**Comment by chapati23** [comment]
@baroooo @nvtaveras i fixed the hard-to-read text:

image

**Review by chapati23 — APPROVED** [review]
lgtm (but i also made some changes, so somebody else should scrutinize my additions more objectively :) )

**Pull request merged**
