### PR TITLE
Fix(137): Button alignment for Create proposal

### LINKED ISSUE #137: [Bug][Low priority] Proposal creation, Wrong back / next button style
Relevant to back / next button in each section of the flow:
- wrong color of the back button;
- wrong padding between input field and the button component;
- wrong horizontal alignment of the buttons.

[Component in Figma](https://www.figma.com/file/QSQsvksBOspBTONiBBFpqa/MENTO-Airdrop-%26-Governance-UIs?type=design&node-id=6719%3A3297&mode=design&t=E12zjKP9aijF3Yni-1)
Implementation:

Image

Design:

Image

### PR DESCRIPTION
**Pull request by RyRy79261**
## Description

This PR fixes some styling issues with the button, ensures no default overlap, removes the unneeded padding on the buttons 

## Related PR

- closes #137

### CODE REVIEW

**Review by bayological — APPROVED** [review]

**Comment by denviljclarke** [comment]
Good work @RyRy79261 , two little design nits

1. The spacing between the inputs is different on the different steps
Description Step - 
Screenshot 2024-05-22 at 4 45 08 PM
Execution Code Step - 
Screenshot 2024-05-22 at 4 45 16 PM

3.  less noticeable - The divider from the design is missing

**Review by denviljclarke — CHANGES_REQUESTED** [review]
Good work @RyRy79261 , two little design nits

1. The spacing between the inputs is different on the different steps
Description Step - 
Screenshot 2024-05-22 at 4 45 08 PM
Execution Code Step - 
Screenshot 2024-05-22 at 4 45 16 PM

2.  less noticeable - The divider from the design is missing

**Comment by RyRy79261** [comment]
@denviljclarke The ticket didn't specify to match the divider between in the updates

**Comment by denviljclarke** [comment]
> @denviljclarke The ticket didn't specify to match the divider between in the updates

You're right, but it's in the photo. We can just leave it to @olenovyk to decide. I think the spacing between the inputs and buttons should be the same on the two steps, though

**Pull request merged**
