### PR TITLE
Feat(109): Connected dropdown style fixes

### LINKED ISSUE #109: Connect dropdown: Styling updates
## Overview

The connected drop down menu is missing some minor styling elements. 

## Acceptance criteria

- [x] Dividers between buttons
- [x] Text & Typography needs to be checked against the styling
- [x] Padding & width needs to be adjusted
- [x] No icons exist for the rainbow kit modal buttons, unsure what to do about that

### PR DESCRIPTION
**Pull request by RyRy79261**
## Overview

This PR fixes some styling mismatches and should now match the designs

## Review process

- Checking the preconnected state in light & dark mode
- Checking post connected for Celo & Alfajores in light & dark mode

## Related issues

- closes #109

### CODE REVIEW

**Review by baroooo — COMMENTED** [review]
Two comments:
Like Bayo mentioned, we miss some icons and also the space between the icon and the text is smaller then the design:
image


and in the dark mode, the style of the connect button is different then the design:
image

**Comment by RyRy79261** [comment]
@baroooo We dont have icons for those buttons available. I looked through the Figma component library and didn't see any appropriate ones

**Comment by RyRy79261** [comment]
@baroooo Ahh its actually a different font in the drop down, made some updates

**Comment by RyRy79261** [comment]
image

**Comment by baroooo** [comment]
> The dark mode design uses a different button all together, so I assumed it was deprecated. There isn't any reference for what the different button styles specifically look like in dark mode, to change the type entirely I'd need to do that via react instead of media queries

If this is ok as it is, the rest looks good ✅

**Review by baroooo — APPROVED** [review]

**Review by bayological — APPROVED** [review]

**Pull request merged**
